name: base64-bytestring-type
version: 0.1.0.0
synopsis: A newtype around ByteString, for base64 encoding
description: A newtype around ByteString, for base64 encoding
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-base64-bytestring-type
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.2, GHC==8.2.1
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base               >=4.7      && <4.11
  - aeson              >=0.8.0.2  && <1.3
  - base64-bytestring  >=1.0.0.1  && <1.1
  - binary             >=0.7.1.0  && <0.10
  - bytestring         >=0.10.4.0 && <0.11
  - cereal             >=0.4.1.1  && <0.6
  - deepseq            >=1.3.0.2  && <1.5
  - hashable           >=1.2.3.3  && <1.3
  - semigroups         >=0.16.2.2 && <0.19
  - text               >=1.2.0.6  && <1.3

library:
  source-dirs: src

tests:
  tests:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - base64-bytestring-type
      - tasty             >=0.10.0.2 && <0.12
      - tasty-quickcheck  >=0.8.3.2  && <0.10
